# In flutter_env_manager/build.yaml
targets:
  $default:
    builders:
      flutter_env_manager|environment_builder:
        enabled: true
        generate_for:
          - environment.yaml

builders:
  environment_builder:
    import: "package:flutter_env_manager/builder.dart"
    builder_factories: ["environmentConfigBuilder"]
#    build_extensions: {"environment.yaml": ["lib/app_environment.dart"]}
    build_extensions: {"environment.yaml": [".dart"]}
    build_to: source
    auto_apply: dependents