import 'dart:io';
import 'package:yaml/yaml.dart';

class EnvManager {
  static const String envFileName = 'environment.yaml';
  static const String envClassFileName = 'lib/app_environment.dart';
  static const String pubspecFileName = 'pubspec.yaml';

  static Future<void> generateEnvClass([String? envArgument]) async {
    final envFile = File(envFileName);
    if (!await envFile.exists()) {
      await _createDefaultEnvFile(envFile);
    }

    final yamlString = await envFile.readAsString();
    final yamlMap = loadYaml(yamlString);

    final currentEnv = envArgument ?? yamlMap['current_environment'];
    final environments = yamlMap['environments'] as Map;

    if (!environments.containsKey(currentEnv)) {
      print('Error: Environment "$currentEnv" does not exist in $envFileName.');

      exit(1);
    }

    final envConfig = environments[currentEnv];
    final appVersion = await _readAppVersion();

    // Generate the AppEnvironment class dynamically
    final classContent = '''
//THIS IS GENERATED FILE DO NOT EDIT THIS FILE

class AppEnvironment {
  static const String currentEnvironment = '$currentEnv';
  static const String version = '$appVersion';
${_generateStaticVariables(envConfig)}
}
''';

    final classFile = File(envClassFileName);
    await classFile.writeAsString(classContent);
  }

  static String _generateStaticVariables(YamlMap envConfig) {
    final buffer = StringBuffer();
    envConfig.forEach((key, value) {
      if (value is String) {
        buffer.writeln(
            "  static const String $key = '${value.replaceAll("'", "\\'")}';");
      } else if (value is num) {
        buffer.writeln(" static const num $key = $value;");
      } else if (value is bool) {
        buffer.writeln(" static const bool $key = $value;");
      } else {
        buffer.writeln(" static const dynamic $key = ${value.toString()};");
      }
    });
    return buffer.toString();
  }

  static Future<String> _readAppVersion() async {
    final pubspecFile = File(pubspecFileName);
    if (!await pubspecFile.exists()) {
      return 'unknown';
    }

    final yamlString = await pubspecFile.readAsString();
    final yamlMap = loadYaml(yamlString);
    return yamlMap['version']?.toString() ?? 'unknown';
  }

  static Future<void> _createDefaultEnvFile(File file) async {
    const defaultYamlContent = '''
environments:
  development:
    baseUrl: https://api.dev.example.com
    apiKey: dev_api_key
  staging:
    baseUrl: https://api.staging.example.com
    apiKey: staging_api_key
  production:
    baseUrl: https://api.example.com
    apiKey: prod_api_key

current_environment: development
''';

    await file.writeAsString(defaultYamlContent);
  }
}
