// import 'dart:io';
//
// import 'package:yaml/yaml.dart';
//
// class EnvManager {
//   static const String envFileName = 'environment.yaml';
//   static const String envClassFileName = 'lib/app_environment.dart';
//
//   static Future<void> generateEnvClass() async {
//     final file = File(envFileName);
//     if (!await file.exists()) {
//       await _createDefaultEnvFile(file);
//     }
//
//     final yamlString = await file.readAsString();
//     final yamlMap = loadYaml(yamlString);
//
//     final currentEnv = yamlMap['current_environment'];
//     final envConfig = yamlMap['environments'][currentEnv];
//
//     // Generate the AppEnvironment class dynamically
//     final classContent = '''
// class AppEnvironment {
//   static const String currentEnvironment = '$currentEnv';
// ${_generateStaticVariables(envConfig)}
// }
// ''';
//
//     final classFile = File(envClassFileName);
//     await classFile.writeAsString(classContent);
//   }
//
//   static String _generateStaticVariables(YamlMap envConfig) {
//     final buffer = StringBuffer();
//     envConfig.forEach((key, value) {
//       if (value is String) {
//         buffer.writeln(
//             "  static const String $key = '${value.replaceAll("'", "\\'")}';");
//       } else if (value is num) {
//         buffer.writeln("  static const num $key = $value;");
//       } else if (value is bool) {
//         buffer.writeln("  static const bool $key = $value;");
//       } else {
//         buffer.writeln("  static const dynamic $key = ${value.toString()};");
//       }
//     });
//     return buffer.toString();
//   }
//
//   static Future<void> _createDefaultEnvFile(File file) async {
//     const defaultYamlContent = '''
// environments:
//   development:
//     base_url: https://api.dev.example.com
//     api_key: dev_api_key
//     custom_var: some_value
//   staging:
//     base_url: https://api.staging.example.com
//     api_key: staging_api_key
//   production:
//     base_url: https://api.example.com
//     api_key: prod_api_key
//
// current_environment: development
// ''';
//
//     await file.writeAsString(defaultYamlContent);
//   }
// }

import 'dart:io';
import 'package:yaml/yaml.dart';

class EnvManager {
  static const String envFileName = 'environment.yaml';
  static const String envClassFileName = 'lib/app_environment.dart';
  static const String pubspecFileName = 'pubspec.yaml';

  static Future<void> generateEnvClass([String? envArgument]) async {
    final envFile = File(envFileName);
    if (!await envFile.exists()) {
      await _createDefaultEnvFile(envFile);
    }

    final yamlString = await envFile.readAsString();
    final yamlMap = loadYaml(yamlString);

    final currentEnv = envArgument ?? yamlMap['current_environment'];
    final environments = yamlMap['environments'] as Map;

    if (!environments.containsKey(currentEnv)) {
      print('Error: Environment "$currentEnv" does not exist in $envFileName.');

      exit(1);
    }

    final envConfig = environments[currentEnv];
    final appVersion = await _readAppVersion();

    // Generate the AppEnvironment class dynamically
    final classContent = '''
//THIS IS GENERATED FILE DO NOT EDIT THIS FILE

class AppEnvironment {
  static const String currentEnvironment = '$currentEnv';
  static const String version = '$appVersion';
${_generateStaticVariables(envConfig)}
}
''';

    final classFile = File(envClassFileName);
    await classFile.writeAsString(classContent);
  }

  static String _generateStaticVariables(YamlMap envConfig) {
    final buffer = StringBuffer();
    envConfig.forEach((key, value) {
      if (value is String) {
        buffer.writeln(
            "  static const String $key = '${value.replaceAll("'", "\\'")}';");
      } else if (value is num) {
        buffer.writeln(" static const num $key = $value;");
      } else if (value is bool) {
        buffer.writeln(" static const bool $key = $value;");
      } else {
        buffer.writeln(" static const dynamic $key = ${value.toString()};");
      }
    });
    return buffer.toString();
  }

  static Future<String> _readAppVersion() async {
    final pubspecFile = File(pubspecFileName);
    if (!await pubspecFile.exists()) {
      return 'unknown';
    }

    final yamlString = await pubspecFile.readAsString();
    final yamlMap = loadYaml(yamlString);
    return yamlMap['version']?.toString() ?? 'unknown';
  }

  static Future<void> _createDefaultEnvFile(File file) async {
    const defaultYamlContent = '''
environments:
  development:
    base_url: https://api.dev.example.com
    api_key: dev_api_key
  staging:
    base_url: https://api.staging.example.com
    api_key: staging_api_key
  production:
    base_url: https://api.example.com
    api_key: prod_api_key

current_environment: development
''';

    await file.writeAsString(defaultYamlContent);
  }
}
